spring.application.name=smartrescue

server.port=8080

# PostgreSQL DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/smartrescue
spring.datasource.username=postgres
spring.datasource.password=Postgres@13
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

